# Liste der Sprachen, für die Sprachserver gestartet werden; Auswahl aus:
#   al               bash             clojure          cpp              csharp           csharp_omnisharp
#   dart             elixir           elm              erlang           fortran          fsharp
#   go               groovy           haskell          java             julia            kotlin
#   lua              markdown         nix              pascal           perl             php
#   powershell       python           python_jedi      r                rego             ruby
#   ruby_solargraph  rust             scala            swift            terraform        toml
#   typescript       typescript_vts   yaml             zig
# Hinweis:
#   - Für C bitte cpp verwenden
#   - Für JavaScript bitte typescript verwenden
#   - Für Free Pascal / Lazarus bitte pascal verwenden
# Besondere Anforderungen:
#   - csharp: Erfordert das Vorhandensein einer .sln-Datei im Projektordner.
#   - pascal: Erfordert den Free Pascal Compiler (fpc) und optional Lazarus.
# Bei Verwendung mehrerer Sprachen wird der erste Sprachserver,
# der eine bestimmte Datei unterstützt, für diese Datei verwendet.
# Die erste Sprache ist die Standardsprache und der entsprechende
# Sprachserver wird als Fallback verwendet.
# Beachte, dass bei Verwendung des JetBrains-Backends keine Sprachserver
# verwendet werden und diese Liste entsprechend ignoriert wird.
languages:
- typescript
- vue

# Die von Textdateien im Projekt verwendete Zeichenkodierung
# Eine Liste möglicher Kodierungen findest du unter:
# https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: "utf-8"

# Gibt an, ob die .gitignore-Datei des Projekts verwendet werden soll,
# um Dateien zu ignorieren
# Hinzugefügt am 2025-04-07
ignore_all_files_in_gitignore: true

# Liste zusätzlicher Pfade, die ignoriert werden sollen
# Gleiche Syntax wie bei gitignore, daher können * und ** verwendet werden
# Hieß zuvor `ignored_dirs`, bitte aktualisiere deine Konfiguration,
# falls du diese noch verwendest.
# Hinzugefügt (umbenannt) am 2025-04-07
ignored_paths: []

# Gibt an, ob sich das Projekt im Nur-Lese-Modus befindet
# Wenn auf true gesetzt, werden alle Bearbeitungswerkzeuge deaktiviert
# und Versuche, sie zu verwenden, führen zu einem Fehler
# Hinzugefügt am 2025-04-18
read_only: false

# Liste von Tool-Namen, die ausgeschlossen werden sollen.
# Wir empfehlen, keine Tools auszuschließen; siehe README für weitere Details.
# Unten ist die vollständige Liste der Tools zur Übersicht aufgeführt.
# Um sicherzustellen, dass du die aktuellste Tool-Liste hast und um
# deren Beschreibungen einzusehen, führe folgenden Befehl aus:
# `uv run scripts/print_tool_overview.py`.
#
#  * `activate_project`: Aktiviert ein Projekt anhand des Namens.
#  * `check_onboarding_performed`: Prüft, ob das Projekt-Onboarding bereits durchgeführt wurde.
#  * `create_text_file`: Erstellt oder überschreibt eine Datei im Projektverzeichnis.
#  * `delete_lines`: Löscht einen Zeilenbereich innerhalb einer Datei.
#  * `delete_memory`: Löscht einen Speicher aus Serenas projektspezifischem Speicher.
#  * `execute_shell_command`: Führt einen Shell-Befehl aus.
#  * `find_referencing_code_snippets`: Findet Code-Snippets, in denen das Symbol an der angegebenen Position referenziert wird.
#  * `find_referencing_symbols`: Findet Symbole, die auf das Symbol an der angegebenen Position verweisen
#     (optional nach Typ gefiltert).
#  * `find_symbol`: Führt eine globale (oder lokale) Suche nach Symbolen mit/enthaltend
#     einen gegebenen Namen/Teilstring durch (optional nach Typ gefiltert).
#  * `get_current_config`: Gibt die aktuelle Konfiguration des Agenten aus,
#     einschließlich aktiver und verfügbarer Projekte, Tools, Kontexte und Modi.
#  * `get_symbols_overview`: Liefert eine Übersicht der auf oberster Ebene
#     definierten Symbole in einer gegebenen Datei.
#  * `initial_instructions`: Gibt die initialen Anweisungen für das aktuelle Projekt zurück.
#     Sollte nur in Umgebungen verwendet werden, in denen der System-Prompt
#     nicht gesetzt werden kann, z. B. in Clients ohne Kontrolle darüber
#     wie Claude Desktop.
#  * `insert_after_symbol`: Fügt Inhalt nach dem Ende der Definition eines gegebenen Symbols ein.
#  * `insert_at_line`: Fügt Inhalt an einer bestimmten Zeile in einer Datei ein.
#  * `insert_before_symbol`: Fügt Inhalt vor dem Beginn der Definition eines gegebenen Symbols ein.
#  * `list_dir`: Listet Dateien und Verzeichnisse im angegebenen Verzeichnis auf
#     (optional rekursiv).
#  * `list_memories`: Listet die Speicher in Serenas projektspezifischem Speicher auf.
#  * `onboarding`: Führt das Onboarding durch
#     (Identifikation der Projektstruktur und wesentlicher Aufgaben,
#     z. B. für Tests oder Builds).
#  * `prepare_for_new_conversation`: Liefert Anweisungen zur Vorbereitung
#     auf eine neue Konversation (um mit dem notwendigen Kontext fortzufahren).
#  * `read_file`: Liest eine Datei innerhalb des Projektverzeichnisses.
#  * `read_memory`: Liest den Speicher mit dem angegebenen Namen
#     aus Serenas projektspezifischem Speicher.
#  * `remove_project`: Entfernt ein Projekt aus der Serena-Konfiguration.
#  * `replace_lines`: Ersetzt einen Zeilenbereich innerhalb einer Datei durch neuen Inhalt.
#  * `replace_symbol_body`: Ersetzt die vollständige Definition eines Symbols.
#  * `restart_language_server`: Startet den Sprachserver neu;
#     kann erforderlich sein, wenn Änderungen außerhalb von Serena vorgenommen wurden.
#  * `search_for_pattern`: Führt eine Suche nach einem Muster im Projekt durch.
#  * `summarize_changes`: Liefert Anweisungen zum Zusammenfassen
#     der am Codebestand vorgenommenen Änderungen.
#  * `switch_modes`: Aktiviert Modi durch Angabe einer Liste ihrer Namen.
#  * `think_about_collected_information`: Denk-Tool zur Bewertung der
#     Vollständigkeit gesammelter Informationen.
#  * `think_about_task_adherence`: Denk-Tool zur Prüfung,
#     ob der Agent noch auf Kurs mit der aktuellen Aufgabe ist.
#  * `think_about_whether_you_are_done`: Denk-Tool zur Prüfung,
#     ob die Aufgabe wirklich abgeschlossen ist.
#  * `write_memory`: Schreibt einen benannten Speicher
#     zur späteren Verwendung in Serenas projektspezifischem Speicher.
excluded_tools: ["write_memory","edit_memory","delete_memory"]

# Initialer Prompt für das Projekt.
# Er wird dem LLM immer beim Aktivieren des Projekts übergeben
# (im Gegensatz zu den Speichern, die nur bei Bedarf geladen werden).
initial_prompt: ""

project_name: "60_HIDEANDSEEK"
included_optional_tools: []
