#!/usr/bin/env bash
set -euo pipefail

# .serena/memories = EPHEMERAL CACHE for Serena (SSoT remains Obsidian Vault)
VAULT_ROOT="${VAULT_ROOT:-/home/akki/vault/DEV_CONTROL_VAULT}"
PROJECT="${PROJECT:-60_HIDEANDSEEK}"

SRC="$VAULT_ROOT/Projectdocs/$PROJECT/_memories"
DEST=".serena/memories"

echo "VAULT_ROOT=$VAULT_ROOT"
echo "PROJECT=$PROJECT"
echo "SRC=$SRC"
echo "DEST=$DEST"
echo

test -d "$SRC" || { echo "ERROR: Missing source memories: $SRC"; exit 1; }
mkdir -p "$DEST"

# deterministic cache wipe
rm -f "$DEST"/*.md

# marker (prevents treating it as authoritative memory)
cat > "$DEST/00__SERENA_MEMORIES_CACHE_README.md" <<'MARK'
---
type: cache
authoritative: false
ssot: "Obsidian Vault"
rule: "DO NOT EDIT. Regenerated by .serena/sync_serena_memories.sh"
---

# Serena Memories Cache (EPHEMERAL)

This folder is a generated cache for tooling convenience.
Single Source of Truth remains in Obsidian (DEV_CONTROL_VAULT).
MARK

# P0 (always): based on your M00 index
for f in \
  "M00_INDEX_60_HIDEANDSEEK.md" \
  "M01_QuickFacts.md" \
  "M05_DevWorkflow.md"
do
  if [ -f "$SRC/$f" ]; then
    cp "$SRC/$f" "$DEST/10_$f"
  else
    echo "WARN: missing P0 memory: $f"
  fi
done

# P1 (optional): include when INCLUDE_P1=1
if [ "${INCLUDE_P1:-0}" = "1" ]; then
  for f in \
    "M02_Architecture.md" \
    "M03_DomainModels.md" \
    "M04_API.md" \
    "M06_CodeQuality.md" \
    "M07_UI_Components_Styling.md" \
    "M08_Testing.md"
  do
    if [ -f "$SRC/$f" ]; then
      cp "$SRC/$f" "$DEST/20_$f"
    else
      echo "WARN: missing P1 memory: $f"
    fi
  done
fi

echo
echo "✅ Synced .serena/memories cache:"
ls -1 "$DEST" | sed 's/^/ - /'
